import type { AppendedRow, SheetRef, SpreadsheetProvider } from './types'
import { columnIndexToLetter } from '../lib/columnLetter'
import { authenticateExcel, getValidExcelToken } from './msAuth'

const GRAPH_BASE = 'https://graph.microsoft.com/v1.0'
// Every workbook this provider creates uses this fixed worksheet name —
// never read back from a response the way GoogleSheetsProvider.createSheet
// does, because the blank-workbook.xlsx template (public/templates/) is
// generated by us with this exact sheet name, not left to Excel's default.
const WORKSHEET_NAME = 'Sheet1'

class GraphApiError extends Error {
  constructor(
    public status: number,
    message: string,
  ) {
    super(message)
  }
}

async function graphFetch(path: string, token: string, init?: RequestInit): Promise<unknown> {
  const res = await fetch(`${GRAPH_BASE}${path}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
      ...(init?.headers ?? {}),
    },
  })
  const bodyText = await res.text()
  if (!res.ok) {
    throw new GraphApiError(res.status, `Graph API ${res.status}: ${bodyText}`)
  }
  return bodyText ? JSON.parse(bodyText) : undefined
}

export const excelProvider: SpreadsheetProvider = {
  async authenticate() {
    await authenticateExcel()
  },

  async createSheet(templateColumns: string[]): Promise<SheetRef> {
    const token = await getValidExcelToken()

    // Lazily initializes "Apps/<app name>" on a OneDrive that's never used
    // this app before — real-confirmed required (a 404 without this call,
    // fixed once this GET was added). See CLAUDE.md ExcelProvider notes.
    await graphFetch('/me/drive/special/approot', token)

    // Timestamped, not fixed — Graph's conflict-behavior story for this
    // specific content-upload-by-path PUT is genuinely unverified (mixed,
    // contradictory reports found during research), so this sidesteps the
    // question entirely by guaranteeing the path never collides, matching
    // GoogleSheetsProvider.createSheet's own guarantee of never
    // overwriting an existing file.
    const fileName = `Job Applications ${Date.now()}.xlsx`
    const templateBytes = await fetch(chrome.runtime.getURL('templates/blank-workbook.xlsx')).then((r) =>
      r.arrayBuffer(),
    )
    const created = (await graphFetch(
      `/me/drive/special/approot:/${encodeURIComponent(fileName)}:/content`,
      token,
      {
        method: 'PUT',
        headers: { 'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' },
        body: templateBytes,
      },
    )) as { id: string; webUrl?: string }
    const itemId = created.id

    // Write the real header text first, then build the Table over that
    // already-populated range with hasHeaders:true — so Excel treats row 1
    // as real header labels, not just structural row 1 of an empty table.
    const lastColumn = columnIndexToLetter(templateColumns.length - 1)
    const headerRange = `A1:${lastColumn}1`
    await graphFetch(`/me/drive/items/${itemId}/workbook/worksheets/${WORKSHEET_NAME}/range(address='${headerRange}')`, token, {
      method: 'PATCH',
      body: JSON.stringify({ values: [templateColumns] }),
    })

    const table = (await graphFetch(
      `/me/drive/items/${itemId}/workbook/worksheets/${WORKSHEET_NAME}/tables/add`,
      token,
      {
        method: 'POST',
        body: JSON.stringify({ address: headerRange, hasHeaders: true }),
      },
    )) as { id: string }

    return { spreadsheetId: itemId, sheetName: WORKSHEET_NAME, tableId: table.id, webUrl: created.webUrl }
  },

  async readHeaders(sheetRef: SheetRef): Promise<string[]> {
    const token = await getValidExcelToken()
    const data = (await graphFetch(
      `/me/drive/items/${sheetRef.spreadsheetId}/workbook/tables/${sheetRef.tableId}/headerRowRange`,
      token,
    )) as { values?: string[][] }
    return data.values?.[0] ?? []
  },

  async appendRow(sheetRef: SheetRef, row: Record<string, string>): Promise<AppendedRow> {
    const token = await getValidExcelToken()
    // Same self-correcting reasoning as GoogleSheetsProvider.appendRow —
    // read the table's actual current headers to determine column order
    // rather than trusting Object.values(row) insertion order.
    const headers = await this.readHeaders(sheetRef)
    const values = headers.map((header) => row[header] ?? '')

    const result = (await graphFetch(`/me/drive/items/${sheetRef.spreadsheetId}/workbook/tables/${sheetRef.tableId}/rows`, token, {
      method: 'POST',
      body: JSON.stringify({ index: null, values: [values] }),
    })) as { index: number }

    // Graph's row `index` is 0-based *within the table's data rows*, not
    // an absolute worksheet row. createSheet always anchors the table's
    // header at worksheet row 1 (A1:{col}1), so data row 0 sits at
    // worksheet row 2 — hence +2. Empirically verified against 3 real
    // sequential appends (indexes 0,1,2 -> rows 2,3,4), not just asserted;
    // see CLAUDE.md ExcelProvider notes for the pasted evidence.
    return { sheetName: sheetRef.sheetName, rowNumber: result.index + 2 }
  },

  async updateCell(sheetRef: SheetRef, rowNumber: number, columnName: string, value: string): Promise<void> {
    const token = await getValidExcelToken()
    const headers = await this.readHeaders(sheetRef)
    const columnIndex = headers.indexOf(columnName)
    if (columnIndex === -1) {
      throw new Error(`Column "${columnName}" not found in table headers: ${headers.join(', ')}`)
    }
    const address = `${columnIndexToLetter(columnIndex)}${rowNumber}`
    await graphFetch(`/me/drive/items/${sheetRef.spreadsheetId}/workbook/worksheets/${sheetRef.sheetName}/range(address='${address}')`, token, {
      method: 'PATCH',
      body: JSON.stringify({ values: [[value]] }),
    })
  },
}
